apiVersion: v1
kind: PersistentVolume
metadata:
  name: splunk-mds-appdata
  namespace: splunk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/splunk-mds"
