apiVersion: v1
kind: PersistentVolume
metadata:
  name: mds-appdata
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/nfserver/mds_appdata"
