apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-mds-config
  namespace: splunk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
