apiVersion: v1
kind: Service
metadata:
  name: splunk-mds-lb
spec:
  selector:
    app: splunk
  ports:
    - port: 32740
      targetPort: 8089
      nodePort: 32740
  externalTrafficPolicy: Local
  type: LoadBalancer
