apiVersion: v1
kind: ConfigMap
metadata:
  namespace: splunk
  name: lb-config
data:
  config: |
    address-pools:
    - name: splunk
      protocol: layer2
      addresses:
      - 10.1.3.10-10.1.3.15
