---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-deploy-server-data
  labels:
    app: splunk
    role: splunk_deploy_server
    tier: sds
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-deploy-config
  labels:
    app: splunk
    role: splunk_deploy_server
    tier: sds
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi