---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: splunk
  name: splunksds
  labels:
    app: splunk
    role: splunksds
    tier: sds
spec:
  replicas: 3
  selector:
    matchLabels:
      app: splunk
      role: splunksds
      tier: sds
  template:
    metadata:
      labels:
        app: splunk
        role: splunksds
        tier: sds 
    spec:
      hostname: sds
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - sds.splunk.svc.cluster.local
      containers:
        - name: splunksds
          image: splunk/splunk:latest
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_ETC
              value: /opt/splunk/etc
            - name: SPLUNK_ROLE
              value: splunk_deploy_server
            - name: SPLUNK_PASSWORD
              value: changeme123
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
          ports:
            - name: web
              containerPort: 8000
            - name: mgmt
              containerPort: 8089
            - name: kv
              containerPort: 8191
