---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sds-data
  namespace: splunk
  labels:
    app: splunk
    role: splunk_deploy_server
    tier: sds
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
