apiVersion: v1
kind: Service
metadata:
  name: splunk-mds-lb
spec:
  selector:
    app: splunk
  ports:
    - name: splunk
      protocol: TCP
      port: 8089
      targetPort: 8089
  externalTrafficPolicy: Local
  type: NodePort
