apiVersion: v1
kind: Service
metadata:
  name: splunk-mds
  namespace: splunk
spec:
  selector:
    app: splunk
  ports:
    - port: 8089
      targetPort: 8089
  externalTrafficPolicy: Local
  type: LoadBalancer
